# Generated by Django 5.0.1 on 2024-02-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0008_staff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
    ]
